version: '3.1'
services:

  proxy:
    image: nginx:latest
    volumes:
      - .docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  leadspeed:
    image: anurag2701/docker-php
    ports:
      - 8080:80
    volumes:
      - .:/var/www


  mysqldb:
    image: mysql:5.6.27
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: leadspeed
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql


networks:
    default:
      external:
        name: leadspeed-dev

volumes:
  mysql_data:
    driver: local
